### ISSUE TITLE
As a NUS Student, I can filter industries that you are interested to intern at

### ISSUE THREAD

**Issue by TanCiKang** [CS2103JAN2018-F11-B3/main#18]
so that I can narrow down the companies to apply for

Model Related
[x ] [v1.3] #16 Database for companies
[x ] Implement a data structure that will be used to temporarily store the Companies / Internship

Complete set of commands required
[x] [v1.1] #17 Find / Search All Command 
[x] [v1.3] #98 Filter Command
[x] [v1.4] #94 Sortby Command 

Useful Features
[] Add / Remove Search (No Longer Doing)
[x]  [v1.4] #92 Enhance AddTags / RemoveTags to work with searching / filtering
[x] [v1.3] #61 Save Internship List

**Comment by niloc94** [comment]
All features done !
