### ISSUE TITLE
Outstanding Issues

### ISSUE THREAD

**Issue by niloc94** [CS2103JAN2018-F11-B3/main#181]
[x] #188  edit boolean attribute for new command
[Cancelled] find salary more / less than number (Update user guide) 
[x] #199  finish up test codes
[] PPP
[] DIAGRAMS (Sequence diagram)
[] populate sample data
[x] #189  remove address/email search string / filter / sort

**Comment by wyinkok** [comment]
Update user guide about whether it sorts in alphabetical order (for strings) and increasing/decreasing order (integers) so it's clearer. 

Also, I think it may be good to give an example how to utilise find versus filter and how they are different because it isn't clear in the user guide now.
